[versions]
json = "20251224"
kotest = "5.9.1"
coroutines = "1.10.2"

[libraries]
json = { module = "org.json:json", version.ref = "json" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
